elixir upgrade, npm upgrades, hex upgrades

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -30,6 +30,7 @@ fi
 # Compile assets
 if git diff --name-only $oldrev $newrev | grep "^assets/"; then
   echo "Compiling assets"
+  npm install || die "assets install failed"
   npm run deploy --prefix ./assets
   mix phx.digest || die "assets compile failed"
 fi
@@ -45,3 +46,4 @@ echo "Building release"
 mix distillery.release --quiet || die "failed to generate release"
 
 _build/prod/rel/philomena/bin/philomena reboot || die "failed to upgrade app; log in to the server and restart the app manually"
+
