use fixed version and emulator reboots for now

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -34,10 +34,14 @@ if git diff --name-only $oldrev $newrev | grep "^assets/"; then
   mix phx.digest || die "assets compile failed"
 fi
 
-# Generate release name to always be the current timestamp so that
-# it will be considered an upgrade
-export PHILOMENA_VERSION="0.1.$(date +%s)"
+# TODO: fix this when I can figure out how to avoid recompiling
+# the entire project when the version changes
+#
+# # Generate release name to always be the current timestamp so that
+# # it will be considered an upgrade
+# export PHILOMENA_VERSION="0.1.$(date +%s)"
 
-mix distillery.release --upgrade || die "failed to generate release"
+echo "Building release"
+mix distillery.release --quiet || die "failed to generate release"
 
-_build/prod/rel/philomena/bin/philomena upgrade $PHILOMENA_VERSION || die "failed to upgrade app; log in to the server and restart the app manually"
+_build/prod/rel/philomena/bin/philomena reboot || die "failed to upgrade app; log in to the server and restart the app manually"
